title: h3sc work
description: well done!
remote_theme: pmarsceill/just-the-docs

url: https://zzinee.github.io/h3sc_repo

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
